### ISSUE TITLE
iCloud problem

### ISSUE THREAD

**Issue by aaaahhhhhh** [bonki/hackintosh-opencore-hp-elitebook-840-g1#1]
Hi i have an issue with iCloud it won't let me sing is and it is showing me this window. Please Help
![Snímek obrazovky 2022-12-07 v 6 27 10](https://user-images.githubusercontent.com/120033432/206205041-b0574429-1679-4fa5-bd36-b31636538a50.png)

**Comment by bonki** [comment]
You will need to follow the relevant steps in the [OpenCore guide](https://dortania.github.io/OpenCore-Post-Install/universal/iservices.html#using-gensmbios) to get iServices to work.
